services:
  apppolicia:
    image: nginx
    expose:
    - 80
    volumes:
      - ./dist:/var/www/
      - ./logs/nginx:/var/log/nginx
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    networks:
      - spa

networks:
  spa:
    name: spa_network
    external: true