export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const INDEX_CATEGORY = 'INDEX_CATEGORY';
export const SHOW_CATEGORY = 'SHOW_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';

export const CREATE_CRIME = 'CREATE_CRIME';