name: "Deploy"
on:
  push:
    branches:
      - main
jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checking out to the repository"
        uses: actions/checkout@v4

      - name: "Set up Node.js"
        uses: actions/setup-node@v3
        with:
          node-version: '18.19.1'

      - name: "Copy .env.example to .env"
        run: |
          cp .env.example .env

      - name: "Update .env values"
        run: |
          sed -i "s#VUE_APP_API_URL=.*#VUE_APP_API_URL=${{ secrets.VUE_APP_API_URL }}#" .env
          sed -i "s#VUE_APP_SPA_URL=.*#VUE_APP_SPA_URL=${{ secrets.VUE_APP_SPA_URL }}#" .env

      - name: "Install dependencies"
        run: |
          npm install

      - name: "Build the front-end app"
        run: |
          npm run build

      - name: "Copying files to the VPS"
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "."
          target: "/root/projects/revoada/app-front"
          overwrite: true
      
      - name: "Restarting Docker Container"
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /root/projects/revoada/app-front
            docker compose restart